#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "📚 CCPM — PM-focused (PRD → Epic → Jira)"
echo "========================================"
echo ""
echo "🎯 Quick start"
echo "  1. /pm:prd-new <name>        - Create a new PRD"
echo "  2. /pm:prd-parse <name>      - Convert PRD to epic"
echo "  3. /pm:epic-decompose <name> - Break into work item files"
echo "  4. /pm:epic-sync <name>      - Push epic + items to Jira"
echo ""
echo "📄 PRD commands"
echo "  /pm:prd-new <name>     - New product requirement"
echo "  /pm:prd-parse <name>   - PRD → epic"
echo "  /pm:prd-list           - List PRDs"
echo "  /pm:prd-edit <name>    - Edit PRD"
echo "  /pm:prd-status         - PRD status"
echo ""
echo "📚 Epic commands"
echo "  /pm:epic-decompose <name> - Decompose into T###.md"
echo "  /pm:epic-sync <name>      - Sync to Jira"
echo "  /pm:epic-oneshot <name>   - Decompose + sync"
echo "  /pm:epic-list             - List epics"
echo "  /pm:epic-show <name>      - Epic + tasks"
echo "  /pm:epic-status [name]    - Progress"
echo "  /pm:epic-close <name>     - Complete epic (local + Jira guidance)"
echo "  /pm:epic-edit <name>      - Edit epic"
echo "  /pm:epic-refresh <name>   - Refresh epic progress from tasks"
echo ""
echo "📝 Issue / work item commands"
echo "  /pm:issue-show <id>       - T### or JIRA-123"
echo "  /pm:issue-status <id>     - Status"
echo "  /pm:issue-close <id>      - Mark complete (local + Jira)"
echo "  /pm:issue-reopen <id>     - Reopen"
echo "  /pm:issue-edit <id>       - Edit work item"
echo ""
echo "🔄 Reporting"
echo "  /pm:next               - Next ready items"
echo "  /pm:status             - Dashboard"
echo "  /pm:standup            - Standup-style summary"
echo "  /pm:blocked            - Blocked items"
echo "  /pm:in-progress        - Items with status in-progress"
echo ""
echo "🔗 Jira"
echo "  /pm:sync               - Sync guidance (see skill sync.md)"
echo "  /pm:import <issue>     - Import from Jira (if configured)"
echo ""
echo "🔧 Maintenance"
echo "  /pm:validate           - Validate structure"
echo "  /pm:clean              - Archive completed work"
echo "  /pm:search <query>     - Search content"
echo ""
echo "⚙️  Setup"
echo "  /pm:init               - Initialize layout"
echo "  /pm:help               - This help"
echo ""
echo "💡 Tip: delivery happens in Jira and your repo; CCPM here is for specs, breakdown, and PM visibility."

exit 0
